#!/bin/bash

# Load software
module load r/4.1.2

# Calculate A and B
A=$((SLURM_ARRAY_TASK_ID % 5 + 1))
B=$((SLURM_ARRAY_TASK_ID % 100 + 1))

# Run R script with command line arguments
R CMD BATCH "--args $A $B" MCMCbird-models.R